name: HTML5 Validator

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check HTML5 format
      - uses: Cyb3r-Jak3/html5validator-action@v0.6
      - with:
          root: /
